UPDATE t_p18520385_fulfillment_platform.fulfillments SET city='Видное',address='г. Видное, Каширское шоссе, 26-й километр, ст. 40',warehouse_area=1000,working_hours='пн-пт 09-19',contact_email='',contact_tg='',website_url='',has_trial=true,work_schemes=ARRAY['FBS','FBO'],marketplaces=ARRAY['Wildberries','Ozon','Яндекс Маркет','СберМегаМаркет'],features=ARRAY['Видеонаблюдение'],packaging_types=ARRAY['Полиэтилен (ПВД)','Коробка (картон)','ВПП','ПОФ'],storage_price='от 1',assembly_price='От 15–20',delivery_price='От 300–500',updated_at=now() WHERE id=52;

UPDATE t_p18520385_fulfillment_platform.fulfillments SET address='Люберцы, р.п. Томилино, Новорязанское шоссе, 23-й километр, корп. 18',warehouse_area=2900,working_hours='круглосуточно',contact_email='info@finedesigngroup.ru',contact_tg='',website_url='',has_trial=false,work_schemes=ARRAY['FBS','FBO'],marketplaces=ARRAY['Wildberries','Ozon','Яндекс Маркет','СберМегаМаркет','Lamoda'],features=ARRAY['Видеонаблюдение','Обработка возвратов','Температурный режим','Фотосъёмка товаров','Маркировка Честный Знак'],packaging_types=ARRAY['Полиэтилен (ПВД)','Коробка (картон)','ВПП','ПОФ','Деревянная обрешётка','Фирменные пакеты','Индивидуальная упаковка'],storage_price='от 7',assembly_price='от 10 ₽ за ед.',delivery_price='от 1 500',updated_at=now() WHERE id=53;

UPDATE t_p18520385_fulfillment_platform.fulfillments SET address='Люберцы, д. Машково, Машковский проезд, д. 23',warehouse_area=500,working_hours='пн-пт 09-18',contact_email='shva.ff@yandex.ru',contact_tg='',website_url='',has_trial=false,work_schemes=ARRAY['FBS','FBO'],marketplaces=ARRAY['Wildberries','Ozon','Яндекс Маркет','СберМегаМаркет'],features=ARRAY['Видеонаблюдение'],packaging_types=ARRAY['Полиэтилен (ПВД)','Коробка (картон)','ВПП','ПОФ'],storage_price='от 60–65 ₽ за 1 м³ в сутки',assembly_price='от 15–20',delivery_price='от 75',updated_at=now() WHERE id=54;

UPDATE t_p18520385_fulfillment_platform.fulfillments SET address='Дмитровский г.о., д. Глазово, стр. 10',warehouse_area=5000,working_hours='Ежедневно с 08 до 20',contact_email='info@patvergroup.ru',contact_tg='',website_url='https://patvergroup.ru/',has_trial=false,work_schemes=ARRAY['FBS','FBO'],marketplaces=ARRAY['Wildberries','Ozon','Яндекс Маркет','СберМегаМаркет'],features=ARRAY['Видеонаблюдение','Обработка возвратов','Температурный режим','Фотосъёмка товаров','Маркировка Честный Знак','Упаковка под ключ'],packaging_types=ARRAY['Полиэтилен (ПВД)','Коробка (картон)','ВПП','ПОФ','Деревянная обрешётка','Фирменные пакеты','Индивидуальная упаковка'],storage_price='от 4',assembly_price='от 25',delivery_price='от 80',updated_at=now() WHERE id=55;

UPDATE t_p18520385_fulfillment_platform.fulfillments SET address='г. Подольск, ул. Станционная, д. 22',warehouse_area=500,working_hours='Ежедневно с 9 до 21',contact_email='info@marlionff.ru',contact_tg='',website_url='',has_trial=false,work_schemes=ARRAY['FBS','FBO','DBS'],marketplaces=ARRAY['Wildberries','Ozon','Яндекс Маркет','СберМегаМаркет','AliExpress','Lamoda','Свой ИМ'],features=ARRAY['Видеонаблюдение','Обработка возвратов','Температурный режим','Фотосъёмка товаров','Опасные грузы','Маркировка Честный Знак','Упаковка под ключ'],packaging_types=ARRAY['Коробка (картон)','ВПП','ПОФ','Деревянная обрешётка','Индивидуальная упаковка'],storage_price='от 65 ₽ за 1 м³ в сутки',assembly_price='от 100–150',delivery_price='от 350',updated_at=now() WHERE id=56;

UPDATE t_p18520385_fulfillment_platform.fulfillments SET address='МО, п. Быково, Аэропортовская ул., 14, корп. 21',warehouse_area=4600,working_hours='Ежедневно, круглосуточно',contact_email='mail@e-fulfillment.ru',contact_tg='',website_url='https://e-fulfillment.ru/',has_trial=true,work_schemes=ARRAY['FBS','FBO','DBS'],marketplaces=ARRAY['Wildberries','Ozon','Яндекс Маркет','СберМегаМаркет','AliExpress','Lamoda','Свой ИМ'],features=ARRAY['Видеонаблюдение','Обработка возвратов','Температурный режим','Фотосъёмка товаров','Опасные грузы','Сборка день в день','Маркировка Честный Знак','Упаковка под ключ'],packaging_types=ARRAY['Полиэтилен (ПВД)','Коробка (картон)','ВПП','ПОФ','Деревянная обрешётка','Индивидуальная упаковка'],storage_price='80',assembly_price='7 руб',delivery_price='500',updated_at=now() WHERE id=57;

UPDATE t_p18520385_fulfillment_platform.fulfillments SET address='Ленинградский проспект, 72, стр. 1',warehouse_area=1800,working_hours='09:00 – 19:00',contact_email='partners@denco.store',contact_tg='',website_url='https://fulfillment.denco.store/',has_trial=false,work_schemes=ARRAY['FBS','FBO'],marketplaces=ARRAY['Wildberries','Ozon','Яндекс Маркет'],features=ARRAY['Видеонаблюдение','Обработка возвратов','Температурный режим','Фотосъёмка товаров'],packaging_types=ARRAY['Коробка (картон)','ВПП','ПОФ','Деревянная обрешётка'],storage_price='по договорённости',assembly_price='по договорённости',delivery_price='по договорённости',updated_at=now() WHERE id=58;

UPDATE t_p18520385_fulfillment_platform.fulfillments SET address='Москва, ул. Красная Сосна, д. 2, корп. 1, стр. 1',founded_year=2009,working_hours='Пн–Пт 09:00–18:00',contact_email='info@ritm-z.com',contact_tg='',website_url='https://ritm-z.ru/',has_trial=false,work_schemes=ARRAY['FBS','FBO'],marketplaces=ARRAY['Wildberries','Ozon','Яндекс Маркет','Lamoda'],features=ARRAY['Видеонаблюдение','Обработка возвратов','Температурный режим'],packaging_types=ARRAY['Полиэтилен (ПВД)','Коробка (картон)','ВПП','ПОФ'],storage_price='от 70 ₽/м³',assembly_price='от 40 ₽ (до 2 ед.)',delivery_price='Включена/по договорённости',updated_at=now() WHERE id=59;

UPDATE t_p18520385_fulfillment_platform.fulfillments SET address='г. Москва, ул. 1-Варшавский проезд, д. 2, стр. 9А',founded_year=2020,warehouse_area=3000,working_hours='Пн–Пт 08:00–18:00, Сб 09:00–15:00',contact_email='at@atiko.ru',contact_tg='',website_url='https://atiko.ru/',has_trial=false,work_schemes=ARRAY['FBS','FBO'],marketplaces=ARRAY['Wildberries','Ozon','Яндекс Маркет'],features=ARRAY['Видеонаблюдение','Обработка возвратов','Температурный режим'],packaging_types=ARRAY['Полиэтилен (ПВД)','Коробка (картон)','ВПП','ПОФ'],storage_price='80 ₽/м³',assembly_price='от 3 ₽/ед',delivery_price='от 400 ₽/короб, от 3 000 ₽/паллет',updated_at=now() WHERE id=60;

UPDATE t_p18520385_fulfillment_platform.fulfillments SET city='Красногорск',address='МО, г. Красногорск, д. Михалково, тер. Мэйджор Сити, здание складского корп., литера 1Б',founded_year=2004,warehouse_area=176000,working_hours='Пн–Пт (по договорённости)',contact_email='',contact_tg='',website_url='https://major-fulfillment.ru/',has_trial=false,work_schemes=ARRAY['FBS','FBO','DBS'],marketplaces=ARRAY['Wildberries','Ozon','Яндекс Маркет','AliExpress','Lamoda','Свой ИМ'],features=ARRAY['Видеонаблюдение','Обработка возвратов','Температурный режим','Фотосъёмка товаров','Опасные грузы','Сборка день в день','Маркировка Честный Знак','Упаковка под ключ'],packaging_types=ARRAY['Полиэтилен (ПВД)','Коробка (картон)','ВПП','ПОФ','Деревянная обрешётка','Фирменные пакеты','Индивидуальная упаковка'],storage_price='по запросу (индивидуальный тариф)',assembly_price='по запросу',delivery_price='по запросу',updated_at=now() WHERE id=61;

UPDATE t_p18520385_fulfillment_platform.fulfillments SET address='Москва, пос. Марушкинское, д. Шарапово, ул. Придорожная, д. 11, стр. 1',founded_year=2012,working_hours='Пн–Пт 09:00–18:00',contact_email='olk3@olk.su',contact_tg='',website_url='https://olk.su/',has_trial=false,work_schemes=ARRAY['FBS'],marketplaces=ARRAY['Wildberries','Ozon','Яндекс Маркет','СберМегаМаркет'],features=ARRAY['Видеонаблюдение','Обработка возвратов','Температурный режим'],packaging_types=ARRAY['Коробка (картон)','ВПП','ПОФ'],storage_price='от 6 ₽',assembly_price='от 23 ₽',delivery_price='от 1 591 ₽',updated_at=now() WHERE id=62;

UPDATE t_p18520385_fulfillment_platform.fulfillments SET address='МО, г.о. Подольск, Индустриальный парк Коледино, 80с1',working_hours='Ежедневно 08:00–20:00',contact_email='info@kitall.ru',contact_tg='',website_url='https://kitall.ru/',has_trial=true,work_schemes=ARRAY['FBS','FBO'],marketplaces=ARRAY['Wildberries','Ozon','Яндекс Маркет','AliExpress'],features=ARRAY['Видеонаблюдение','Обработка возвратов','Температурный режим'],packaging_types=ARRAY['Полиэтилен (ПВД)','Коробка (картон)','ВПП','ПОФ'],storage_price='от 7 ₽',assembly_price='по запросу',delivery_price='от 1000 руб паллет',updated_at=now() WHERE id=63;

UPDATE t_p18520385_fulfillment_platform.fulfillments SET city='Новосёлки',address='МО, д. Новосёлки, Технопарк, 18 ст1; юр. адрес: Москва, ул. Очаковское шоссе, д. 36',founded_year=2020,warehouse_area=4785,working_hours='Пн–Вс 09:00–19:00',contact_email='info@logixpro.ru',contact_tg='',website_url='https://logixpro.ru/',has_trial=false,work_schemes=ARRAY['FBS','FBO'],marketplaces=ARRAY['Wildberries','Ozon','Яндекс Маркет'],features=ARRAY['Видеонаблюдение','Обработка возвратов','Температурный режим'],packaging_types=ARRAY['Полиэтилен (ПВД)','Коробка (картон)','ВПП','ПОФ'],storage_price='от 0,22 ₽',assembly_price='от 24,20 ₽',delivery_price='по запросу',updated_at=now() WHERE id=64;

UPDATE t_p18520385_fulfillment_platform.fulfillments SET city='Реутов',address='МО, г. Реутов, ул. Фабричная, д. 7',working_hours='Пн–Сб 09:00–19:00',contact_email='info@4-pack.ru',contact_tg='',website_url='https://4-pack.ru/',has_trial=false,work_schemes=ARRAY['FBS','FBO'],marketplaces=ARRAY['Wildberries','Ozon','Яндекс Маркет'],features=ARRAY['Видеонаблюдение'],packaging_types=ARRAY['Полиэтилен (ПВД)','Коробка (картон)','ВПП','ПОФ','Деревянная обрешётка','Индивидуальная упаковка'],storage_price='по договорённости',assembly_price='по запросу',delivery_price='по запросу',updated_at=now() WHERE id=65;

UPDATE t_p18520385_fulfillment_platform.fulfillments SET address='г. Москва, ул. Дубининская, д. 57',founded_year=2019,working_hours='Пн–Пт 09:00–18:00',contact_email='sales@fulex.pro',contact_tg='',website_url='https://fulex.pro/contacts/',has_trial=true,work_schemes=ARRAY['FBS','FBO'],marketplaces=ARRAY['Wildberries','Ozon','Яндекс Маркет'],features=ARRAY['Видеонаблюдение','Обработка возвратов','Температурный режим','Упаковка под ключ'],packaging_types=ARRAY['Полиэтилен (ПВД)','Коробка (картон)','ВПП','ПОФ','Индивидуальная упаковка'],storage_price='от 0.10 ₽',assembly_price='от 2.00 ₽',delivery_price='по запросу',updated_at=now() WHERE id=66;

UPDATE t_p18520385_fulfillment_platform.fulfillments SET city='Горки Ленинские',address='МО, Ленинский г/о, раб. пос. Горки Ленинские, ул. Зелёное шоссе, вл. 4, стр. 1',warehouse_area=1000,working_hours='',contact_email='info@expedit.pro',contact_tg='',website_url='https://expedit.pro/l',has_trial=false,work_schemes=ARRAY['FBS','FBO'],marketplaces=ARRAY['Wildberries','Ozon','Яндекс Маркет'],features=ARRAY['Температурный режим'],packaging_types=ARRAY['Коробка (картон)','ВПП','ПОФ','Фирменные пакеты'],storage_price='по запросу',assembly_price='по запросу',delivery_price='по запросу',updated_at=now() WHERE id=67;

UPDATE t_p18520385_fulfillment_platform.fulfillments SET address='г. Москва, ул. Дорожная, д. 3 с 4А',founded_year=2020,working_hours='10:00–22:00 (ежедневно)',contact_email='controlcenter@internet.ru',contact_tg='@Sofy_marketplace',website_url='https://controlfulfillment.ru/',has_trial=false,work_schemes=ARRAY['FBS','FBO'],marketplaces=ARRAY['Wildberries','Ozon','Яндекс Маркет'],features=ARRAY['Видеонаблюдение','Обработка возвратов','Температурный режим'],packaging_types=ARRAY['Полиэтилен (ПВД)'],storage_price='н/д',assembly_price='от 500 за палет',delivery_price='от 1500 за короб',updated_at=now() WHERE id=68;

UPDATE t_p18520385_fulfillment_platform.fulfillments SET city='Богородский',address='МО, Богородский г/о, пос. Зелёный, Школьная ул., 2с10',founded_year=2021,working_hours='с 09:00 до 20:00 часов',contact_email='welcome@fulllog.ru',contact_tg='',website_url='https://fulllog.ru/',has_trial=false,work_schemes=ARRAY['FBS','FBO','DBS'],marketplaces=ARRAY['Wildberries','Ozon','Яндекс Маркет','СберМегаМаркет'],features=ARRAY['Видеонаблюдение','Обработка возвратов','Температурный режим','Маркировка Честный Знак','Упаковка под ключ'],packaging_types=ARRAY['Полиэтилен (ПВД)','Коробка (картон)','ВПП','ПОФ','Индивидуальная упаковка'],storage_price='по запросу',assembly_price='по запросу',delivery_price='по запросу',updated_at=now() WHERE id=69;
