UPDATE t_p18520385_fulfillment_platform.fulfillments SET address='г. Подольск, мкр. Климовск, ул. Коммунальная, д. 17',warehouse_area=100000,working_hours='пн-пт с 09 до 20',contact_email='info@ao-sdt.ru',contact_tg='',website_url='https://ao-sdt.ru/',has_trial=false,work_schemes=ARRAY['FBS','FBO','DBS'],marketplaces=ARRAY['Wildberries','Ozon','Яндекс Маркет','СберМегаМаркет','AliExpress','Lamoda','Свой ИМ'],features=ARRAY['Видеонаблюдение','Обработка возвратов','Температурный режим','Фотосъёмка товаров','Сборка день в день','Маркировка Честный Знак','Упаковка под ключ'],packaging_types=ARRAY['Полиэтилен (ПВД)','Коробка (картон)','ВПП','ПОФ','Деревянная обрешётка','Фирменные пакеты','Индивидуальная упаковка'],storage_price='от 58 коп./шт',assembly_price='от 8 руб./шт',delivery_price='от 30 руб./шт',updated_at=now() WHERE id=29;

UPDATE t_p18520385_fulfillment_platform.fulfillments SET address='Москва, ул.4-я Гражданская, д.33/1',warehouse_area=300,working_hours='пн-вс с 10 до 21',contact_email='2457365@mail.ru',contact_tg='https://t.me/FULFILMENT_REAL',website_url='https://dostavka-do-marketplace.ru/',has_trial=false,work_schemes=ARRAY['FBS','FBO','DBS','Экспресс доставка'],marketplaces=ARRAY['Wildberries','Ozon','Яндекс Маркет','СберМегаМаркет','AliExpress','Lamoda','Свой ИМ'],features=ARRAY['Видеонаблюдение','Обработка возвратов','Температурный режим','Фотосъёмка товаров','Опасные грузы','Сборка день в день','Маркировка Честный Знак','Упаковка под ключ'],packaging_types=ARRAY['Полиэтилен (ПВД)','Коробка (картон)','ВПП','ПОФ','Деревянная обрешётка','Индивидуальная упаковка'],storage_price='от 0.2 руб',assembly_price='от 25',delivery_price='от 1990',updated_at=now() WHERE id=30;

UPDATE t_p18520385_fulfillment_platform.fulfillments SET city='Домодедово',address='Домодедово Центральный микрорайон владение Вега-в с1',warehouse_area=500,working_hours='пн-вс с 8 до 21',contact_email='info@full-express.ru',contact_tg='@FulExpressMSK',website_url='https://fulexpress.com/',has_trial=false,work_schemes=ARRAY['FBS','FBO'],marketplaces=ARRAY['Wildberries','Ozon','Яндекс Маркет','AliExpress'],features=ARRAY['Обработка возвратов','Опасные грузы','Маркировка Честный Знак'],packaging_types=ARRAY['Полиэтилен (ПВД)','Коробка (картон)','ВПП','ПОФ','Деревянная обрешётка','Индивидуальная упаковка'],storage_price='около 50 ₽ за 1 м³ в сутки',assembly_price='от 16',delivery_price='от 160',updated_at=now() WHERE id=31;

UPDATE t_p18520385_fulfillment_platform.fulfillments SET address='4-й Лихачевский переулок д.9',warehouse_area=11000,working_hours='пн-пт 09-21',contact_email='info@sadovod24.com',contact_tg='',website_url='https://sadovod-24.ru/contacts',has_trial=false,work_schemes=ARRAY['FBS','FBO'],marketplaces=ARRAY['Wildberries','Ozon','Яндекс Маркет','AliExpress'],features=ARRAY['Видеонаблюдение','Обработка возвратов','Температурный режим','Фотосъёмка товаров','Маркировка Честный Знак','Упаковка под ключ'],packaging_types=ARRAY['Полиэтилен (ПВД)','Коробка (картон)','ВПП','ПОФ','Деревянная обрешётка','Фирменные пакеты','Индивидуальная упаковка'],storage_price='от 10,5',assembly_price='от 25',delivery_price='от 1 500',updated_at=now() WHERE id=32;

UPDATE t_p18520385_fulfillment_platform.fulfillments SET address='г. Москва, Каширский проезд, д. 5',warehouse_area=2500,working_hours='пн-вс с 9 до 21',contact_email='boostff@yandex.ru',contact_tg='@boost_ff',website_url='',has_trial=true,work_schemes=ARRAY['FBS','FBO','DBS'],marketplaces=ARRAY['Wildberries','Ozon','Яндекс Маркет','СберМегаМаркет'],features=ARRAY['Видеонаблюдение','Обработка возвратов','Температурный режим','Сборка день в день','Маркировка Честный Знак','Упаковка под ключ'],packaging_types=ARRAY['Полиэтилен (ПВД)','Коробка (картон)','ВПП','ПОФ','Индивидуальная упаковка'],storage_price='от 0,5',assembly_price='от 25',delivery_price='от 160',updated_at=now() WHERE id=33;

UPDATE t_p18520385_fulfillment_platform.fulfillments SET address='г. Москва, Каширское шоссе, д. 19, корп. 2',warehouse_area=500,working_hours='пн-вс с 9 до 21',contact_email='ff.speedoflight@gmail.com',contact_tg='',website_url='https://speedoflightmsk.ru/',has_trial=true,work_schemes=ARRAY['FBS','FBO'],marketplaces=ARRAY['Wildberries','Ozon','Яндекс Маркет','СберМегаМаркет'],features=ARRAY['Видеонаблюдение','Обработка возвратов','Опасные грузы','Маркировка Честный Знак','Упаковка под ключ'],packaging_types=ARRAY['Полиэтилен (ПВД)','Коробка (картон)','ВПП','Фирменные пакеты','Индивидуальная упаковка'],storage_price='от 7',assembly_price='2,5',delivery_price='от 300',updated_at=now() WHERE id=34;

UPDATE t_p18520385_fulfillment_platform.fulfillments SET address='Московская обл., г. Подольск, ул.Чистова, 12',working_hours='Ежедневно, круглосуточно',contact_email='mullogistic@gmail.com',contact_tg='',website_url='https://mul-fulfillment.ru/',has_trial=true,work_schemes=ARRAY['FBS','FBO','DBS'],marketplaces=ARRAY['Wildberries','Ozon','Яндекс Маркет','AliExpress'],features=ARRAY['Видеонаблюдение','Обработка возвратов','Температурный режим','Опасные грузы','Маркировка Честный Знак','Упаковка под ключ'],packaging_types=ARRAY['Полиэтилен (ПВД)','Коробка (картон)','ВПП','ПОФ','Деревянная обрешётка','Индивидуальная упаковка'],storage_price='1 паллето-место 90 ₽',assembly_price='3 ₽ / шт',delivery_price='весом от 35 кг, 80 ₽',updated_at=now() WHERE id=35;

UPDATE t_p18520385_fulfillment_platform.fulfillments SET address='г. Дзержинский, Академика Жукова 8А стр.1',warehouse_area=500,working_hours='8:00 до 17:00',contact_email='sadovodfbs@gmail.com',contact_tg='',website_url='https://xn--80aafaq0aslg3b7f.xn--p1ai/',has_trial=false,work_schemes=ARRAY['FBS','FBO'],marketplaces=ARRAY['Wildberries','Ozon'],features=ARRAY['Видеонаблюдение','Обработка возвратов','Температурный режим','Фотосъёмка товаров','Маркировка Честный Знак','Упаковка под ключ'],packaging_types=ARRAY['Полиэтилен (ПВД)','Коробка (картон)','ВПП','ПОФ','Индивидуальная упаковка'],storage_price='1 кубометр 70 руб./сутки',assembly_price='от 25 руб',delivery_price='от 25 руб',updated_at=now() WHERE id=36;

UPDATE t_p18520385_fulfillment_platform.fulfillments SET city='Москва, Ховрино',address='Московская область, г. Видное, промзона. Северная промзона, влд. 16',warehouse_area=15000,working_hours='Ежедневно, круглосуточно',contact_email='info@yunu.ru',contact_tg='',website_url='https://yunu.ru/',has_trial=false,work_schemes=ARRAY['FBS','FBO'],marketplaces=ARRAY['Wildberries','Ozon','Яндекс Маркет'],features=ARRAY['Видеонаблюдение','Обработка возвратов','Температурный режим','Фотосъёмка товаров','Опасные грузы','Сборка день в день','Маркировка Честный Знак','Упаковка под ключ'],packaging_types=ARRAY['Коробка (картон)','ВПП','ПОФ'],storage_price='от 35 р/паллета в сутки',assembly_price='от 9 р',delivery_price='от 1000 р/паллета',updated_at=now() WHERE id=37;

UPDATE t_p18520385_fulfillment_platform.fulfillments SET city='Растуново',address='Ул. Заря, 52, село Растуново',warehouse_area=432,working_hours='с 08:00 до 20:00',contact_email='Skladoteka@mail.ru',contact_tg='',website_url='https://skladoteka.ru/',has_trial=false,work_schemes=ARRAY['FBS','FBO'],marketplaces=ARRAY['Wildberries','Ozon','Яндекс Маркет'],features=ARRAY['Видеонаблюдение','Обработка возвратов','Температурный режим','Фотосъёмка товаров'],packaging_types=ARRAY['Коробка (картон)','ВПП','ПОФ','Индивидуальная упаковка'],storage_price='25 ₽',assembly_price='8 ₽ / шт',delivery_price='от 5 до 300 рублей',updated_at=now() WHERE id=38;

UPDATE t_p18520385_fulfillment_platform.fulfillments SET city='Москва, Чертаново Северное',address='Москва, улица Чертановская д.9, стр.5',warehouse_area=865,working_hours='10:00 до 21:00',contact_email='helpmeberries@gmail.com',contact_tg='',website_url='https://helpberries.ru/',has_trial=false,work_schemes=ARRAY['FBS','FBO'],marketplaces=ARRAY['Wildberries','Ozon','Яндекс Маркет','СберМегаМаркет','AliExpress','Lamoda','Свой ИМ'],features=ARRAY['Видеонаблюдение','Обработка возвратов','Температурный режим','Фотосъёмка товаров','Опасные грузы','Сборка день в день','Маркировка Честный Знак','Упаковка под ключ'],packaging_types=ARRAY['Полиэтилен (ПВД)','Коробка (картон)','ВПП','ПОФ','Фирменные пакеты','Индивидуальная упаковка'],storage_price='от 30 ₽',assembly_price='10 ₽ / шт',delivery_price='500',updated_at=now() WHERE id=39;

UPDATE t_p18520385_fulfillment_platform.fulfillments SET city='Москва и Московская область',address='Москва, 1-й Варшавский проезд, 2, стр. 21',warehouse_area=850,working_hours='09:00–22:00',contact_email='sale@expressrms.ru',contact_tg='',website_url='https://expressrms.ru/',has_trial=false,work_schemes=ARRAY['FBS','FBO','DBS','Экспресс доставка'],marketplaces=ARRAY['Wildberries','Ozon','Яндекс Маркет','СберМегаМаркет','AliExpress'],features=ARRAY['Видеонаблюдение','Обработка возвратов','Температурный режим','Фотосъёмка товаров','Сборка день в день','Маркировка Честный Знак','Упаковка под ключ'],packaging_types=ARRAY['Полиэтилен (ПВД)','Коробка (картон)','ВПП','ПОФ','Деревянная обрешётка','Индивидуальная упаковка'],storage_price='от 0,02 руб',assembly_price='от 29,99 руб.',delivery_price='349',updated_at=now() WHERE id=40;

UPDATE t_p18520385_fulfillment_platform.fulfillments SET city='Москва и Московская область',address='1-й Варшавский пр-д, д.2, стр. 9А',warehouse_area=6160,working_hours='8:00 до 20:00',contact_email='info@teamdeem.ru',contact_tg='',website_url='https://teamdeem.ru/',has_trial=true,work_schemes=ARRAY['FBS','FBO','DBS'],marketplaces=ARRAY['Wildberries','Ozon','Яндекс Маркет'],features=ARRAY['Видеонаблюдение','Обработка возвратов','Температурный режим','Фотосъёмка товаров','Опасные грузы','Сборка день в день','Маркировка Честный Знак','Упаковка под ключ'],packaging_types=ARRAY['Полиэтилен (ПВД)','Коробка (картон)','ВПП','ПОФ','Индивидуальная упаковка'],storage_price='65–70 рублей в сутки.',assembly_price='7 руб',delivery_price='от 2000 ₽ за паллет.',updated_at=now() WHERE id=41;

UPDATE t_p18520385_fulfillment_platform.fulfillments SET city='Быково',address='МО, Раменский г.о., д. Быково, ул. Аэропортовская, 14; Москва, 2-й Котляковский пер., 1 ст37',founded_year=2017,warehouse_area=145000,working_hours='Пн–Вс 09:00–21:00',contact_email='sales@kak2c.ru',contact_tg='',website_url='https://kak2c.ru/',has_trial=false,work_schemes=ARRAY['FBS','FBO'],marketplaces=ARRAY['Wildberries','Ozon','Яндекс Маркет','СберМегаМаркет','AliExpress','Lamoda','Свой ИМ'],features=ARRAY['Видеонаблюдение','Обработка возвратов','Температурный режим','Фотосъёмка товаров','Опасные грузы','Маркировка Честный Знак','Упаковка под ключ'],packaging_types=ARRAY['Полиэтилен (ПВД)','Коробка (картон)','ВПП','ПОФ','Деревянная обрешётка','Индивидуальная упаковка'],storage_price='от 1,3 ₽',assembly_price='от 60,5 ₽',delivery_price='от 200 ₽',updated_at=now() WHERE id=42;

UPDATE t_p18520385_fulfillment_platform.fulfillments SET address='Москва, ул. 1-я Измайловского Зверинца, д. 8; МО, г. Люберцы, п. Чкалово, ул. Будённого, д. 16А',founded_year=2020,working_hours='Пн–Вс 09:00–21:00',contact_email='sales@ffcdek.ru',contact_tg='',website_url='https://ff.cdek.ru/contacts',has_trial=false,work_schemes=ARRAY['FBS','FBO','DBS'],marketplaces=ARRAY['Wildberries','Ozon','Яндекс Маркет','СберМегаМаркет','AliExpress','Lamoda','Свой ИМ'],features=ARRAY['Видеонаблюдение','Обработка возвратов','Температурный режим','Маркировка Честный Знак'],packaging_types=ARRAY['Полиэтилен (ПВД)','Коробка (картон)','ПОФ'],storage_price='от 1,3 ₽',assembly_price='от 35 ₽',delivery_price='по тарифу',updated_at=now() WHERE id=43;

UPDATE t_p18520385_fulfillment_platform.fulfillments SET address='МО, Подольск, ул. Шамотная, 3',founded_year=2017,warehouse_area=800,working_hours='Пн–Вс 09:00–21:00',contact_email='sales@upmarket.cc',contact_tg='',website_url='https://www.upmarket.cc/',has_trial=false,work_schemes=ARRAY['FBS','FBO'],marketplaces=ARRAY['Wildberries','Ozon','Яндекс Маркет'],features=ARRAY['Видеонаблюдение'],packaging_types=ARRAY['Полиэтилен (ПВД)','Коробка (картон)','ВПП','ПОФ','Деревянная обрешётка'],storage_price='по запросу',assembly_price='по запросу',delivery_price='по запросу',updated_at=now() WHERE id=44;

UPDATE t_p18520385_fulfillment_platform.fulfillments SET address='Москва, ул. 4-я Кабельная, д. 6А; ул. 2-я Кабельная, д. 2, стр. 6',founded_year=2015,warehouse_area=19000,working_hours='круглосуточно',contact_email='sales@betapro.ru',contact_tg='',website_url='https://betapro.ru/',has_trial=false,work_schemes=ARRAY['FBS','FBO','DBS'],marketplaces=ARRAY['Wildberries','Ozon','Яндекс Маркет','AliExpress','Lamoda'],features=ARRAY['Видеонаблюдение','Обработка возвратов','Температурный режим','Фотосъёмка товаров','Опасные грузы','Маркировка Честный Знак','Упаковка под ключ'],packaging_types=ARRAY['Полиэтилен (ПВД)','Коробка (картон)','ПОФ','Деревянная обрешётка','Индивидуальная упаковка'],storage_price='от 0,20 ₽',assembly_price='от 21,50 ₽',delivery_price='от 22,50 ₽/шт.',updated_at=now() WHERE id=45;

UPDATE t_p18520385_fulfillment_platform.fulfillments SET city='Москва / Подольск',address='МКАД, 32-й км, вл. 4, Москва; МО, Подольск, ул. Комсомольская, 1, с. 22',working_hours='Пн–Вс 09:00–20:00',contact_email='ffpartners@mail.ru',contact_tg='',website_url='https://ffpartners.ru/',has_trial=false,work_schemes=ARRAY['FBS','FBO'],marketplaces=ARRAY['Wildberries','Ozon','Яндекс Маркет'],features=ARRAY['Видеонаблюдение'],packaging_types=ARRAY['Полиэтилен (ПВД)','Коробка (картон)','ВПП','ПОФ','Деревянная обрешётка'],storage_price='от 0,10 ₽',assembly_price='от 120 ₽',delivery_price='от 200 ₽',updated_at=now() WHERE id=46;

UPDATE t_p18520385_fulfillment_platform.fulfillments SET address='г. Люберцы, ул. Волковская, 70',founded_year=2020,warehouse_area=1700,working_hours='Пн–Вс, 9:00–19:00 (МСК)',contact_email='mscntr@gmail.com',contact_tg='',website_url='https://www.upseller.pro/',has_trial=false,work_schemes=ARRAY['FBS','FBO'],marketplaces=ARRAY['Wildberries','Ozon','Яндекс Маркет'],features=ARRAY['Видеонаблюдение','Обработка возвратов','Температурный режим','Фотосъёмка товаров','Маркировка Честный Знак','Упаковка под ключ'],packaging_types=ARRAY['Полиэтилен (ПВД)','Коробка (картон)','ВПП','ПОФ','Индивидуальная упаковка'],storage_price='от 8 ₽',assembly_price='от 5 ₽',delivery_price='от 6 ₽',updated_at=now() WHERE id=47;

UPDATE t_p18520385_fulfillment_platform.fulfillments SET address='Московская обл., г.о. Люберцы, рп. Томилино, территория Логистический Центр, лит14П',founded_year=2010,working_hours='9:00–19:00, без выходных',contact_email='hello@fffree.ru',contact_tg='https://t.me/feelfullfree',website_url='https://fffree.ru/',has_trial=false,work_schemes=ARRAY['FBS'],marketplaces=ARRAY['Wildberries','Ozon','Яндекс Маркет','СберМегаМаркет','AliExpress'],features=ARRAY['Видеонаблюдение','Температурный режим','Обработка возвратов','Фотосъёмка товаров'],packaging_types=ARRAY['Полиэтилен (ПВД)','ВПП','ПОФ','Деревянная обрешётка'],storage_price='по запросу',assembly_price='по запросу',delivery_price='по запросу',updated_at=now() WHERE id=48;

UPDATE t_p18520385_fulfillment_platform.fulfillments SET address='Москва, Тихорецкий бульвар, 1с3',warehouse_area=1500,working_hours='Ежедневно 09:00–22:00',contact_email='info.ff.evo@gmail.com',contact_tg='',website_url='https://fulfilment-evolution.ru/',has_trial=true,work_schemes=ARRAY['FBS','FBO'],marketplaces=ARRAY['Wildberries','Ozon','Яндекс Маркет','СберМегаМаркет','AliExpress'],features=ARRAY['Видеонаблюдение','Обработка возвратов','Температурный режим','Фотосъёмка товаров','Маркировка Честный Знак','Упаковка под ключ'],packaging_types=ARRAY['Полиэтилен (ПВД)','Коробка (картон)','ВПП','Индивидуальная упаковка'],storage_price='от 39 ₽ за палет',assembly_price='от 8 руб',delivery_price='от 500 руб',updated_at=now() WHERE id=49;

UPDATE t_p18520385_fulfillment_platform.fulfillments SET address='Москва, ул. Хабарова д. 2',founded_year=2018,warehouse_area=850,working_hours='Пн–Сб, 7:00–18:00',contact_email='info@lpspack.ru',contact_tg='@lpskontrol',website_url='https://lpspack.ru/',has_trial=false,work_schemes=ARRAY['FBS','FBO','Экспресс доставка'],marketplaces=ARRAY['Wildberries','Ozon','AliExpress'],features=ARRAY['Видеонаблюдение','Обработка возвратов','Температурный режим','Фотосъёмка товаров','Маркировка Честный Знак','Упаковка под ключ'],packaging_types=ARRAY['Полиэтилен (ПВД)','Коробка (картон)','ВПП','ПОФ'],storage_price='200 ₽ за паллет',assembly_price='от 15 ₽',delivery_price='от 500 ₽',updated_at=now() WHERE id=50;
